### ISSUE TITLE
Formatting issue on iPad Pro (12.9 - inch)(2nd Generation)

### ISSUE THREAD

**Issue by clfristoe** [kirankalyan5/react-native-segmented-control-tab#67] opened 2018-08-10 20:17 UTC
Noticing the divider between the second and third tab is not visible unless I tap and hold the third tab.
![simulator screen shot - ipad pro 12 9-inch 2nd generation - 2018-08-10 at 15 12 10](https://user-images.githubusercontent.com/15655814/43979454-71b3d7da-9cb0-11e8-821e-d0856750777c.png)

**Comment by kirankalyan5** [comment] 2018-08-10 20:57
Thanks for reporting! Does it work fine on Phone? 

Could you share the [snack](https://snack.expo.io/) for the same, so I could give a try fixing it.

**Comment by clfristoe** [comment] 2018-08-10 21:08
Yes, it works fine on iPhone, only iPad sizes (I think it's a width issue). Due to business policy, I cannot share all the code, but this is the main file that we use. I've uploaded it as a snack, but it doesn't compile. https://snack.expo.io/HJkwCdoBQ

**Comment by kirankalyan5** [comment] 2018-11-28 09:01
Couldn't reproduce, Closing it for now.

**Closed by kirankalyan5** 2018-11-28 09:01 UTC
